/*
 * generated by Xtext 2.12.0
 */
package de.fraunhofer.ipa.ide.contentassist.antlr;

import com.google.inject.Inject;
import de.fraunhofer.ipa.ide.contentassist.antlr.internal.InternalRosSystemParser;
import de.fraunhofer.ipa.services.RosSystemGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class RosSystemParser extends AbstractContentAssistParser {

	@Inject
	private RosSystemGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalRosSystemParser createParser() {
		InternalRosSystemParser result = new InternalRosSystemParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getNamespaceAccess().getAlternatives(), "rule__Namespace__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getRosSystemAccess().getGroup(), "rule__RosSystem__Group__0");
					put(grammarAccess.getRosSystemAccess().getGroup_3(), "rule__RosSystem__Group_3__0");
					put(grammarAccess.getRosSystemAccess().getGroup_4(), "rule__RosSystem__Group_4__0");
					put(grammarAccess.getRosSystemAccess().getGroup_5(), "rule__RosSystem__Group_5__0");
					put(grammarAccess.getRosSystemAccess().getGroup_5_3(), "rule__RosSystem__Group_5_3__0");
					put(grammarAccess.getRosSystemAccess().getGroup_6(), "rule__RosSystem__Group_6__0");
					put(grammarAccess.getRosSystemAccess().getGroup_6_3(), "rule__RosSystem__Group_6_3__0");
					put(grammarAccess.getTopicConnectionAccess().getGroup(), "rule__TopicConnection__Group__0");
					put(grammarAccess.getTopicConnectionAccess().getGroup_3(), "rule__TopicConnection__Group_3__0");
					put(grammarAccess.getTopicConnectionAccess().getGroup_4(), "rule__TopicConnection__Group_4__0");
					put(grammarAccess.getServiceConnectionAccess().getGroup(), "rule__ServiceConnection__Group__0");
					put(grammarAccess.getServiceConnectionAccess().getGroup_3(), "rule__ServiceConnection__Group_3__0");
					put(grammarAccess.getServiceConnectionAccess().getGroup_4(), "rule__ServiceConnection__Group_4__0");
					put(grammarAccess.getComponentInterfaceAccess().getGroup(), "rule__ComponentInterface__Group__0");
					put(grammarAccess.getComponentInterfaceAccess().getGroup_4(), "rule__ComponentInterface__Group_4__0");
					put(grammarAccess.getComponentInterfaceAccess().getGroup_5(), "rule__ComponentInterface__Group_5__0");
					put(grammarAccess.getComponentInterfaceAccess().getGroup_6(), "rule__ComponentInterface__Group_6__0");
					put(grammarAccess.getComponentInterfaceAccess().getGroup_7(), "rule__ComponentInterface__Group_7__0");
					put(grammarAccess.getComponentInterfaceAccess().getGroup_8(), "rule__ComponentInterface__Group_8__0");
					put(grammarAccess.getPublisherAccess().getGroup(), "rule__Publisher__Group__0");
					put(grammarAccess.getPublisherAccess().getGroup_3(), "rule__Publisher__Group_3__0");
					put(grammarAccess.getPublisherAccess().getGroup_4(), "rule__Publisher__Group_4__0");
					put(grammarAccess.getPublisherAccess().getGroup_5(), "rule__Publisher__Group_5__0");
					put(grammarAccess.getSubscriberAccess().getGroup(), "rule__Subscriber__Group__0");
					put(grammarAccess.getSubscriberAccess().getGroup_3(), "rule__Subscriber__Group_3__0");
					put(grammarAccess.getSubscriberAccess().getGroup_4(), "rule__Subscriber__Group_4__0");
					put(grammarAccess.getSubscriberAccess().getGroup_5(), "rule__Subscriber__Group_5__0");
					put(grammarAccess.getPublisher0Access().getGroup(), "rule__Publisher0__Group__0");
					put(grammarAccess.getPublisher0Access().getGroup_6(), "rule__Publisher0__Group_6__0");
					put(grammarAccess.getTopicSpecAccess().getGroup(), "rule__TopicSpec__Group__0");
					put(grammarAccess.getTopicSpecAccess().getGroup_4(), "rule__TopicSpec__Group_4__0");
					put(grammarAccess.getMessageDefinitionAccess().getGroup(), "rule__MessageDefinition__Group__0");
					put(grammarAccess.getGlobalNamespaceAccess().getGroup(), "rule__GlobalNamespace__Group__0");
					put(grammarAccess.getGlobalNamespaceAccess().getGroup_3(), "rule__GlobalNamespace__Group_3__0");
					put(grammarAccess.getGlobalNamespaceAccess().getGroup_3_3(), "rule__GlobalNamespace__Group_3_3__0");
					put(grammarAccess.getRelativeNamespace_ImplAccess().getGroup(), "rule__RelativeNamespace_Impl__Group__0");
					put(grammarAccess.getRelativeNamespace_ImplAccess().getGroup_3(), "rule__RelativeNamespace_Impl__Group_3__0");
					put(grammarAccess.getRelativeNamespace_ImplAccess().getGroup_3_3(), "rule__RelativeNamespace_Impl__Group_3_3__0");
					put(grammarAccess.getPrivateNamespaceAccess().getGroup(), "rule__PrivateNamespace__Group__0");
					put(grammarAccess.getPrivateNamespaceAccess().getGroup_3(), "rule__PrivateNamespace__Group_3__0");
					put(grammarAccess.getPrivateNamespaceAccess().getGroup_3_3(), "rule__PrivateNamespace__Group_3_3__0");
					put(grammarAccess.getSubscriber0Access().getGroup(), "rule__Subscriber0__Group__0");
					put(grammarAccess.getSubscriber0Access().getGroup_6(), "rule__Subscriber0__Group_6__0");
					put(grammarAccess.getServiceServerAccess().getGroup(), "rule__ServiceServer__Group__0");
					put(grammarAccess.getServiceServerAccess().getGroup_3(), "rule__ServiceServer__Group_3__0");
					put(grammarAccess.getServiceServerAccess().getGroup_4(), "rule__ServiceServer__Group_4__0");
					put(grammarAccess.getServiceServerAccess().getGroup_5(), "rule__ServiceServer__Group_5__0");
					put(grammarAccess.getServiceClientAccess().getGroup(), "rule__ServiceClient__Group__0");
					put(grammarAccess.getServiceClientAccess().getGroup_3(), "rule__ServiceClient__Group_3__0");
					put(grammarAccess.getServiceClientAccess().getGroup_4(), "rule__ServiceClient__Group_4__0");
					put(grammarAccess.getServiceClientAccess().getGroup_5(), "rule__ServiceClient__Group_5__0");
					put(grammarAccess.getServiceServer0Access().getGroup(), "rule__ServiceServer0__Group__0");
					put(grammarAccess.getServiceServer0Access().getGroup_6(), "rule__ServiceServer0__Group_6__0");
					put(grammarAccess.getServiceSpecAccess().getGroup(), "rule__ServiceSpec__Group__0");
					put(grammarAccess.getServiceSpecAccess().getGroup_4(), "rule__ServiceSpec__Group_4__0");
					put(grammarAccess.getServiceSpecAccess().getGroup_5(), "rule__ServiceSpec__Group_5__0");
					put(grammarAccess.getServiceClient0Access().getGroup(), "rule__ServiceClient0__Group__0");
					put(grammarAccess.getServiceClient0Access().getGroup_6(), "rule__ServiceClient0__Group_6__0");
					put(grammarAccess.getRosSystemAccess().getNameAssignment_3_1(), "rule__RosSystem__NameAssignment_3_1");
					put(grammarAccess.getRosSystemAccess().getRosComponentAssignment_4_1(), "rule__RosSystem__RosComponentAssignment_4_1");
					put(grammarAccess.getRosSystemAccess().getTopicConnectionsAssignment_5_2(), "rule__RosSystem__TopicConnectionsAssignment_5_2");
					put(grammarAccess.getRosSystemAccess().getTopicConnectionsAssignment_5_3_1(), "rule__RosSystem__TopicConnectionsAssignment_5_3_1");
					put(grammarAccess.getRosSystemAccess().getServiceConnectionsAssignment_6_2(), "rule__RosSystem__ServiceConnectionsAssignment_6_2");
					put(grammarAccess.getRosSystemAccess().getServiceConnectionsAssignment_6_3_1(), "rule__RosSystem__ServiceConnectionsAssignment_6_3_1");
					put(grammarAccess.getTopicConnectionAccess().getFromAssignment_3_1(), "rule__TopicConnection__FromAssignment_3_1");
					put(grammarAccess.getTopicConnectionAccess().getToAssignment_4_1(), "rule__TopicConnection__ToAssignment_4_1");
					put(grammarAccess.getServiceConnectionAccess().getFromAssignment_3_1(), "rule__ServiceConnection__FromAssignment_3_1");
					put(grammarAccess.getServiceConnectionAccess().getToAssignment_4_1(), "rule__ServiceConnection__ToAssignment_4_1");
					put(grammarAccess.getComponentInterfaceAccess().getNameAssignment_3(), "rule__ComponentInterface__NameAssignment_3");
					put(grammarAccess.getComponentInterfaceAccess().getNamespaceAssignment_4_1(), "rule__ComponentInterface__NamespaceAssignment_4_1");
					put(grammarAccess.getComponentInterfaceAccess().getRosTopicPublisherAssignment_5_1(), "rule__ComponentInterface__RosTopicPublisherAssignment_5_1");
					put(grammarAccess.getComponentInterfaceAccess().getRosTopicSubscriberAssignment_6_1(), "rule__ComponentInterface__RosTopicSubscriberAssignment_6_1");
					put(grammarAccess.getComponentInterfaceAccess().getRosServiceServerAssignment_7_1(), "rule__ComponentInterface__RosServiceServerAssignment_7_1");
					put(grammarAccess.getComponentInterfaceAccess().getRosServiceClientAssignment_8_1(), "rule__ComponentInterface__RosServiceClientAssignment_8_1");
					put(grammarAccess.getPublisherAccess().getTopicNameAssignment_3_1(), "rule__Publisher__TopicNameAssignment_3_1");
					put(grammarAccess.getPublisherAccess().getTopicRefAssignment_4_1(), "rule__Publisher__TopicRefAssignment_4_1");
					put(grammarAccess.getPublisherAccess().getNameSpaceAssignment_5_1(), "rule__Publisher__NameSpaceAssignment_5_1");
					put(grammarAccess.getSubscriberAccess().getTopicNameAssignment_3_1(), "rule__Subscriber__TopicNameAssignment_3_1");
					put(grammarAccess.getSubscriberAccess().getTopicRefAssignment_4_1(), "rule__Subscriber__TopicRefAssignment_4_1");
					put(grammarAccess.getSubscriberAccess().getNameSpaceAssignment_5_1(), "rule__Subscriber__NameSpaceAssignment_5_1");
					put(grammarAccess.getPublisher0Access().getNameAssignment_3(), "rule__Publisher0__NameAssignment_3");
					put(grammarAccess.getPublisher0Access().getMessageAssignment_5(), "rule__Publisher0__MessageAssignment_5");
					put(grammarAccess.getPublisher0Access().getNamespaceAssignment_6_1(), "rule__Publisher0__NamespaceAssignment_6_1");
					put(grammarAccess.getTopicSpecAccess().getNameAssignment_2(), "rule__TopicSpec__NameAssignment_2");
					put(grammarAccess.getTopicSpecAccess().getMessageAssignment_4_1(), "rule__TopicSpec__MessageAssignment_4_1");
					put(grammarAccess.getGlobalNamespaceAccess().getPartsAssignment_3_2(), "rule__GlobalNamespace__PartsAssignment_3_2");
					put(grammarAccess.getGlobalNamespaceAccess().getPartsAssignment_3_3_1(), "rule__GlobalNamespace__PartsAssignment_3_3_1");
					put(grammarAccess.getRelativeNamespace_ImplAccess().getPartsAssignment_3_2(), "rule__RelativeNamespace_Impl__PartsAssignment_3_2");
					put(grammarAccess.getRelativeNamespace_ImplAccess().getPartsAssignment_3_3_1(), "rule__RelativeNamespace_Impl__PartsAssignment_3_3_1");
					put(grammarAccess.getPrivateNamespaceAccess().getPartsAssignment_3_2(), "rule__PrivateNamespace__PartsAssignment_3_2");
					put(grammarAccess.getPrivateNamespaceAccess().getPartsAssignment_3_3_1(), "rule__PrivateNamespace__PartsAssignment_3_3_1");
					put(grammarAccess.getSubscriber0Access().getNameAssignment_3(), "rule__Subscriber0__NameAssignment_3");
					put(grammarAccess.getSubscriber0Access().getMessageAssignment_5(), "rule__Subscriber0__MessageAssignment_5");
					put(grammarAccess.getSubscriber0Access().getNamespaceAssignment_6_1(), "rule__Subscriber0__NamespaceAssignment_6_1");
					put(grammarAccess.getServiceServerAccess().getServiceNameAssignment_3_1(), "rule__ServiceServer__ServiceNameAssignment_3_1");
					put(grammarAccess.getServiceServerAccess().getSrvRefAssignment_4_1(), "rule__ServiceServer__SrvRefAssignment_4_1");
					put(grammarAccess.getServiceServerAccess().getNameSpaceAssignment_5_1(), "rule__ServiceServer__NameSpaceAssignment_5_1");
					put(grammarAccess.getServiceClientAccess().getServiceNameAssignment_3_1(), "rule__ServiceClient__ServiceNameAssignment_3_1");
					put(grammarAccess.getServiceClientAccess().getSrvRefAssignment_4_1(), "rule__ServiceClient__SrvRefAssignment_4_1");
					put(grammarAccess.getServiceClientAccess().getNameSpaceAssignment_5_1(), "rule__ServiceClient__NameSpaceAssignment_5_1");
					put(grammarAccess.getServiceServer0Access().getNameAssignment_3(), "rule__ServiceServer0__NameAssignment_3");
					put(grammarAccess.getServiceServer0Access().getServiceAssignment_5(), "rule__ServiceServer0__ServiceAssignment_5");
					put(grammarAccess.getServiceServer0Access().getNamespaceAssignment_6_1(), "rule__ServiceServer0__NamespaceAssignment_6_1");
					put(grammarAccess.getServiceSpecAccess().getNameAssignment_2(), "rule__ServiceSpec__NameAssignment_2");
					put(grammarAccess.getServiceSpecAccess().getRequestAssignment_4_1(), "rule__ServiceSpec__RequestAssignment_4_1");
					put(grammarAccess.getServiceSpecAccess().getResponseAssignment_5_1(), "rule__ServiceSpec__ResponseAssignment_5_1");
					put(grammarAccess.getServiceClient0Access().getNameAssignment_3(), "rule__ServiceClient0__NameAssignment_3");
					put(grammarAccess.getServiceClient0Access().getServiceAssignment_5(), "rule__ServiceClient0__ServiceAssignment_5");
					put(grammarAccess.getServiceClient0Access().getNamespaceAssignment_6_1(), "rule__ServiceClient0__NamespaceAssignment_6_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RosSystemGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RosSystemGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
