/*
 * generated by Xtext 2.12.0
 */
package de.fraunhofer.ipa


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RosSystemStandaloneSetup extends RosSystemStandaloneSetupGenerated {

	def static void doSetup() {
		new RosSystemStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
