/*
 * generated by Xtext 2.12.0
 */
package de.fraunhofer.ipa.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RosSystemGrammarAccess extends AbstractGrammarElementFinder {
	
	public class RosSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.RosSystem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRosSystemAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRosSystemKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRosComponentKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRosComponentAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cRosComponentComponentInterfaceCrossReference_4_1_0 = (CrossReference)cRosComponentAssignment_4_1.eContents().get(0);
		private final RuleCall cRosComponentComponentInterfaceEStringParserRuleCall_4_1_0_1 = (RuleCall)cRosComponentComponentInterfaceCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTopicConnectionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cTopicConnectionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cTopicConnectionsTopicConnectionParserRuleCall_5_2_0 = (RuleCall)cTopicConnectionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cTopicConnectionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cTopicConnectionsTopicConnectionParserRuleCall_5_3_1_0 = (RuleCall)cTopicConnectionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cServiceConnectionsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cServiceConnectionsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cServiceConnectionsServiceConnectionParserRuleCall_6_2_0 = (RuleCall)cServiceConnectionsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cServiceConnectionsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cServiceConnectionsServiceConnectionParserRuleCall_6_3_1_0 = (RuleCall)cServiceConnectionsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RosSystem:
		//	{RosSystem}
		//	'RosSystem'
		//	'{' ('Name' Name=EString)? ('RosComponent' RosComponent+=[componentInterface::ComponentInterface|EString])?
		//	('TopicConnections' '{' TopicConnections+=TopicConnection ("," TopicConnections+=TopicConnection)* '}')?
		//	('ServiceConnections' '{' ServiceConnections+=ServiceConnection ("," ServiceConnections+=ServiceConnection)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RosSystem} 'RosSystem' '{' ('Name' Name=EString)? ('RosComponent'
		//RosComponent+=[componentInterface::ComponentInterface|EString])? ('TopicConnections' '{'
		//TopicConnections+=TopicConnection ("," TopicConnections+=TopicConnection)* '}')? ('ServiceConnections' '{'
		//ServiceConnections+=ServiceConnection ("," ServiceConnections+=ServiceConnection)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{RosSystem}
		public Action getRosSystemAction_0() { return cRosSystemAction_0; }
		
		//'RosSystem'
		public Keyword getRosSystemKeyword_1() { return cRosSystemKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('Name' Name=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'Name'
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }
		
		//Name=EString
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_1_0() { return cNameEStringParserRuleCall_3_1_0; }
		
		//('RosComponent' RosComponent+=[componentInterface::ComponentInterface|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'RosComponent'
		public Keyword getRosComponentKeyword_4_0() { return cRosComponentKeyword_4_0; }
		
		//RosComponent+=[componentInterface::ComponentInterface|EString]
		public Assignment getRosComponentAssignment_4_1() { return cRosComponentAssignment_4_1; }
		
		//[componentInterface::ComponentInterface|EString]
		public CrossReference getRosComponentComponentInterfaceCrossReference_4_1_0() { return cRosComponentComponentInterfaceCrossReference_4_1_0; }
		
		//EString
		public RuleCall getRosComponentComponentInterfaceEStringParserRuleCall_4_1_0_1() { return cRosComponentComponentInterfaceEStringParserRuleCall_4_1_0_1; }
		
		//('TopicConnections' '{' TopicConnections+=TopicConnection ("," TopicConnections+=TopicConnection)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'TopicConnections'
		public Keyword getTopicConnectionsKeyword_5_0() { return cTopicConnectionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//TopicConnections+=TopicConnection
		public Assignment getTopicConnectionsAssignment_5_2() { return cTopicConnectionsAssignment_5_2; }
		
		//TopicConnection
		public RuleCall getTopicConnectionsTopicConnectionParserRuleCall_5_2_0() { return cTopicConnectionsTopicConnectionParserRuleCall_5_2_0; }
		
		//("," TopicConnections+=TopicConnection)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//TopicConnections+=TopicConnection
		public Assignment getTopicConnectionsAssignment_5_3_1() { return cTopicConnectionsAssignment_5_3_1; }
		
		//TopicConnection
		public RuleCall getTopicConnectionsTopicConnectionParserRuleCall_5_3_1_0() { return cTopicConnectionsTopicConnectionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('ServiceConnections' '{' ServiceConnections+=ServiceConnection ("," ServiceConnections+=ServiceConnection)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'ServiceConnections'
		public Keyword getServiceConnectionsKeyword_6_0() { return cServiceConnectionsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//ServiceConnections+=ServiceConnection
		public Assignment getServiceConnectionsAssignment_6_2() { return cServiceConnectionsAssignment_6_2; }
		
		//ServiceConnection
		public RuleCall getServiceConnectionsServiceConnectionParserRuleCall_6_2_0() { return cServiceConnectionsServiceConnectionParserRuleCall_6_2_0; }
		
		//("," ServiceConnections+=ServiceConnection)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//ServiceConnections+=ServiceConnection
		public Assignment getServiceConnectionsAssignment_6_3_1() { return cServiceConnectionsAssignment_6_3_1; }
		
		//ServiceConnection
		public RuleCall getServiceConnectionsServiceConnectionParserRuleCall_6_3_1_0() { return cServiceConnectionsServiceConnectionParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class NamespaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.Namespace");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cGlobalNamespaceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRelativeNamespace_ImplParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPrivateNamespaceParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Namespace ros::Namespace:
		//	GlobalNamespace | RelativeNamespace_Impl | PrivateNamespace;
		@Override public ParserRule getRule() { return rule; }
		
		//GlobalNamespace | RelativeNamespace_Impl | PrivateNamespace
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//GlobalNamespace
		public RuleCall getGlobalNamespaceParserRuleCall_0() { return cGlobalNamespaceParserRuleCall_0; }
		
		//RelativeNamespace_Impl
		public RuleCall getRelativeNamespace_ImplParserRuleCall_1() { return cRelativeNamespace_ImplParserRuleCall_1; }
		
		//PrivateNamespace
		public RuleCall getPrivateNamespaceParserRuleCall_2() { return cPrivateNamespaceParserRuleCall_2; }
	}
	public class TopicConnectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.TopicConnection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTopicConnectionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTopicConnectionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFromKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFromAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cFromPublisherCrossReference_3_1_0 = (CrossReference)cFromAssignment_3_1.eContents().get(0);
		private final RuleCall cFromPublisherEStringParserRuleCall_3_1_0_1 = (RuleCall)cFromPublisherCrossReference_3_1_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cToKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cToAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cToSubscriberCrossReference_4_1_0 = (CrossReference)cToAssignment_4_1.eContents().get(0);
		private final RuleCall cToSubscriberEStringParserRuleCall_4_1_0_1 = (RuleCall)cToSubscriberCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//TopicConnection:
		//	{TopicConnection}
		//	'TopicConnection'
		//	'{' ('From' From=[componentInterface::Publisher|EString])? ('To' To=[componentInterface::Subscriber|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{TopicConnection} 'TopicConnection' '{' ('From' From=[componentInterface::Publisher|EString])? ('To'
		//To=[componentInterface::Subscriber|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{TopicConnection}
		public Action getTopicConnectionAction_0() { return cTopicConnectionAction_0; }
		
		//'TopicConnection'
		public Keyword getTopicConnectionKeyword_1() { return cTopicConnectionKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('From' From=[componentInterface::Publisher|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'From'
		public Keyword getFromKeyword_3_0() { return cFromKeyword_3_0; }
		
		//From=[componentInterface::Publisher|EString]
		public Assignment getFromAssignment_3_1() { return cFromAssignment_3_1; }
		
		//[componentInterface::Publisher|EString]
		public CrossReference getFromPublisherCrossReference_3_1_0() { return cFromPublisherCrossReference_3_1_0; }
		
		//EString
		public RuleCall getFromPublisherEStringParserRuleCall_3_1_0_1() { return cFromPublisherEStringParserRuleCall_3_1_0_1; }
		
		//('To' To=[componentInterface::Subscriber|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'To'
		public Keyword getToKeyword_4_0() { return cToKeyword_4_0; }
		
		//To=[componentInterface::Subscriber|EString]
		public Assignment getToAssignment_4_1() { return cToAssignment_4_1; }
		
		//[componentInterface::Subscriber|EString]
		public CrossReference getToSubscriberCrossReference_4_1_0() { return cToSubscriberCrossReference_4_1_0; }
		
		//EString
		public RuleCall getToSubscriberEStringParserRuleCall_4_1_0_1() { return cToSubscriberEStringParserRuleCall_4_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ServiceConnectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.ServiceConnection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cServiceConnectionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cServiceConnectionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFromKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFromAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cFromServiceServerCrossReference_3_1_0 = (CrossReference)cFromAssignment_3_1.eContents().get(0);
		private final RuleCall cFromServiceServerEStringParserRuleCall_3_1_0_1 = (RuleCall)cFromServiceServerCrossReference_3_1_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cToKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cToAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cToServiceClientCrossReference_4_1_0 = (CrossReference)cToAssignment_4_1.eContents().get(0);
		private final RuleCall cToServiceClientEStringParserRuleCall_4_1_0_1 = (RuleCall)cToServiceClientCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ServiceConnection:
		//	{ServiceConnection}
		//	'ServiceConnection'
		//	'{' ('From' From=[componentInterface::ServiceServer|EString])? ('To' To=[componentInterface::ServiceClient|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ServiceConnection} 'ServiceConnection' '{' ('From' From=[componentInterface::ServiceServer|EString])? ('To'
		//To=[componentInterface::ServiceClient|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{ServiceConnection}
		public Action getServiceConnectionAction_0() { return cServiceConnectionAction_0; }
		
		//'ServiceConnection'
		public Keyword getServiceConnectionKeyword_1() { return cServiceConnectionKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('From' From=[componentInterface::ServiceServer|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'From'
		public Keyword getFromKeyword_3_0() { return cFromKeyword_3_0; }
		
		//From=[componentInterface::ServiceServer|EString]
		public Assignment getFromAssignment_3_1() { return cFromAssignment_3_1; }
		
		//[componentInterface::ServiceServer|EString]
		public CrossReference getFromServiceServerCrossReference_3_1_0() { return cFromServiceServerCrossReference_3_1_0; }
		
		//EString
		public RuleCall getFromServiceServerEStringParserRuleCall_3_1_0_1() { return cFromServiceServerEStringParserRuleCall_3_1_0_1; }
		
		//('To' To=[componentInterface::ServiceClient|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'To'
		public Keyword getToKeyword_4_0() { return cToKeyword_4_0; }
		
		//To=[componentInterface::ServiceClient|EString]
		public Assignment getToAssignment_4_1() { return cToAssignment_4_1; }
		
		//[componentInterface::ServiceClient|EString]
		public CrossReference getToServiceClientCrossReference_4_1_0() { return cToServiceClientCrossReference_4_1_0; }
		
		//EString
		public RuleCall getToServiceClientEStringParserRuleCall_4_1_0_1() { return cToServiceClientEStringParserRuleCall_4_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ComponentInterfaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.ComponentInterface");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComponentInterfaceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNamespaceKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNamespaceAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNamespaceNamespaceParserRuleCall_4_1_0 = (RuleCall)cNamespaceAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPublisherKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRosTopicPublisherAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRosTopicPublisherPublisherParserRuleCall_5_1_0 = (RuleCall)cRosTopicPublisherAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSubscriberKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cRosTopicSubscriberAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cRosTopicSubscriberSubscriberParserRuleCall_6_1_0 = (RuleCall)cRosTopicSubscriberAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cServiceServerKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cRosServiceServerAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cRosServiceServerServiceServerParserRuleCall_7_1_0 = (RuleCall)cRosServiceServerAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cServiceClientKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cRosServiceClientAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cRosServiceClientServiceClientParserRuleCall_8_1_0 = (RuleCall)cRosServiceClientAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//ComponentInterface componentInterface::ComponentInterface:
		//	'ComponentInterface'
		//	'{'
		//	'name' name=EString ('namespace' namespace=Namespace)? ('publisher' RosTopicPublisher+=Publisher)? ('subscriber'
		//	RosTopicSubscriber+=Subscriber)? ('serviceServer' RosServiceServer+=ServiceServer)? ('serviceClient'
		//	RosServiceClient+=ServiceClient)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ComponentInterface' '{' 'name' name=EString ('namespace' namespace=Namespace)? ('publisher'
		//RosTopicPublisher+=Publisher)? ('subscriber' RosTopicSubscriber+=Subscriber)? ('serviceServer'
		//RosServiceServer+=ServiceServer)? ('serviceClient' RosServiceClient+=ServiceClient)? '}'
		public Group getGroup() { return cGroup; }
		
		//'ComponentInterface'
		public Keyword getComponentInterfaceKeyword_0() { return cComponentInterfaceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'name'
		public Keyword getNameKeyword_2() { return cNameKeyword_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//('namespace' namespace=Namespace)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'namespace'
		public Keyword getNamespaceKeyword_4_0() { return cNamespaceKeyword_4_0; }
		
		//namespace=Namespace
		public Assignment getNamespaceAssignment_4_1() { return cNamespaceAssignment_4_1; }
		
		//Namespace
		public RuleCall getNamespaceNamespaceParserRuleCall_4_1_0() { return cNamespaceNamespaceParserRuleCall_4_1_0; }
		
		//('publisher' RosTopicPublisher+=Publisher)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'publisher'
		public Keyword getPublisherKeyword_5_0() { return cPublisherKeyword_5_0; }
		
		//RosTopicPublisher+=Publisher
		public Assignment getRosTopicPublisherAssignment_5_1() { return cRosTopicPublisherAssignment_5_1; }
		
		//Publisher
		public RuleCall getRosTopicPublisherPublisherParserRuleCall_5_1_0() { return cRosTopicPublisherPublisherParserRuleCall_5_1_0; }
		
		//('subscriber' RosTopicSubscriber+=Subscriber)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'subscriber'
		public Keyword getSubscriberKeyword_6_0() { return cSubscriberKeyword_6_0; }
		
		//RosTopicSubscriber+=Subscriber
		public Assignment getRosTopicSubscriberAssignment_6_1() { return cRosTopicSubscriberAssignment_6_1; }
		
		//Subscriber
		public RuleCall getRosTopicSubscriberSubscriberParserRuleCall_6_1_0() { return cRosTopicSubscriberSubscriberParserRuleCall_6_1_0; }
		
		//('serviceServer' RosServiceServer+=ServiceServer)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'serviceServer'
		public Keyword getServiceServerKeyword_7_0() { return cServiceServerKeyword_7_0; }
		
		//RosServiceServer+=ServiceServer
		public Assignment getRosServiceServerAssignment_7_1() { return cRosServiceServerAssignment_7_1; }
		
		//ServiceServer
		public RuleCall getRosServiceServerServiceServerParserRuleCall_7_1_0() { return cRosServiceServerServiceServerParserRuleCall_7_1_0; }
		
		//('serviceClient' RosServiceClient+=ServiceClient)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'serviceClient'
		public Keyword getServiceClientKeyword_8_0() { return cServiceClientKeyword_8_0; }
		
		//RosServiceClient+=ServiceClient
		public Assignment getRosServiceClientAssignment_8_1() { return cRosServiceClientAssignment_8_1; }
		
		//ServiceClient
		public RuleCall getRosServiceClientServiceClientParserRuleCall_8_1_0() { return cRosServiceClientServiceClientParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class PublisherElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.Publisher");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPublisherAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPublisherKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTopicNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTopicNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTopicNameEStringParserRuleCall_3_1_0 = (RuleCall)cTopicNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTopicRefKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTopicRefAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cTopicRefPublisherCrossReference_4_1_0 = (CrossReference)cTopicRefAssignment_4_1.eContents().get(0);
		private final RuleCall cTopicRefPublisherEStringParserRuleCall_4_1_0_1 = (RuleCall)cTopicRefPublisherCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cNameSpaceKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cNameSpaceAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cNameSpaceNamespaceCrossReference_5_1_0 = (CrossReference)cNameSpaceAssignment_5_1.eContents().get(0);
		private final RuleCall cNameSpaceNamespaceEStringParserRuleCall_5_1_0_1 = (RuleCall)cNameSpaceNamespaceCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Publisher componentInterface::Publisher:
		//	{componentInterface::Publisher}
		//	'Publisher'
		//	'{' ('TopicName' TopicName=EString)? ('TopicRef' TopicRef=[ros::Publisher|EString])? ('NameSpace'
		//	NameSpace=[ros::Namespace|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{componentInterface::Publisher} 'Publisher' '{' ('TopicName' TopicName=EString)? ('TopicRef'
		//TopicRef=[ros::Publisher|EString])? ('NameSpace' NameSpace=[ros::Namespace|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{componentInterface::Publisher}
		public Action getPublisherAction_0() { return cPublisherAction_0; }
		
		//'Publisher'
		public Keyword getPublisherKeyword_1() { return cPublisherKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('TopicName' TopicName=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'TopicName'
		public Keyword getTopicNameKeyword_3_0() { return cTopicNameKeyword_3_0; }
		
		//TopicName=EString
		public Assignment getTopicNameAssignment_3_1() { return cTopicNameAssignment_3_1; }
		
		//EString
		public RuleCall getTopicNameEStringParserRuleCall_3_1_0() { return cTopicNameEStringParserRuleCall_3_1_0; }
		
		//('TopicRef' TopicRef=[ros::Publisher|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'TopicRef'
		public Keyword getTopicRefKeyword_4_0() { return cTopicRefKeyword_4_0; }
		
		//TopicRef=[ros::Publisher|EString]
		public Assignment getTopicRefAssignment_4_1() { return cTopicRefAssignment_4_1; }
		
		//[ros::Publisher|EString]
		public CrossReference getTopicRefPublisherCrossReference_4_1_0() { return cTopicRefPublisherCrossReference_4_1_0; }
		
		//EString
		public RuleCall getTopicRefPublisherEStringParserRuleCall_4_1_0_1() { return cTopicRefPublisherEStringParserRuleCall_4_1_0_1; }
		
		//('NameSpace' NameSpace=[ros::Namespace|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'NameSpace'
		public Keyword getNameSpaceKeyword_5_0() { return cNameSpaceKeyword_5_0; }
		
		//NameSpace=[ros::Namespace|EString]
		public Assignment getNameSpaceAssignment_5_1() { return cNameSpaceAssignment_5_1; }
		
		//[ros::Namespace|EString]
		public CrossReference getNameSpaceNamespaceCrossReference_5_1_0() { return cNameSpaceNamespaceCrossReference_5_1_0; }
		
		//EString
		public RuleCall getNameSpaceNamespaceEStringParserRuleCall_5_1_0_1() { return cNameSpaceNamespaceEStringParserRuleCall_5_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class SubscriberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.Subscriber");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSubscriberAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSubscriberKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTopicNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTopicNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTopicNameEStringParserRuleCall_3_1_0 = (RuleCall)cTopicNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTopicRefKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTopicRefAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cTopicRefSubscriberCrossReference_4_1_0 = (CrossReference)cTopicRefAssignment_4_1.eContents().get(0);
		private final RuleCall cTopicRefSubscriberEStringParserRuleCall_4_1_0_1 = (RuleCall)cTopicRefSubscriberCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cNameSpaceKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cNameSpaceAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cNameSpaceNamespaceCrossReference_5_1_0 = (CrossReference)cNameSpaceAssignment_5_1.eContents().get(0);
		private final RuleCall cNameSpaceNamespaceEStringParserRuleCall_5_1_0_1 = (RuleCall)cNameSpaceNamespaceCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Subscriber componentInterface::Subscriber:
		//	{componentInterface::Subscriber}
		//	'Subscriber'
		//	'{' ('TopicName' TopicName=EString)? ('TopicRef' TopicRef=[ros::Subscriber|EString])? ('NameSpace'
		//	NameSpace=[ros::Namespace|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{componentInterface::Subscriber} 'Subscriber' '{' ('TopicName' TopicName=EString)? ('TopicRef'
		//TopicRef=[ros::Subscriber|EString])? ('NameSpace' NameSpace=[ros::Namespace|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{componentInterface::Subscriber}
		public Action getSubscriberAction_0() { return cSubscriberAction_0; }
		
		//'Subscriber'
		public Keyword getSubscriberKeyword_1() { return cSubscriberKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('TopicName' TopicName=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'TopicName'
		public Keyword getTopicNameKeyword_3_0() { return cTopicNameKeyword_3_0; }
		
		//TopicName=EString
		public Assignment getTopicNameAssignment_3_1() { return cTopicNameAssignment_3_1; }
		
		//EString
		public RuleCall getTopicNameEStringParserRuleCall_3_1_0() { return cTopicNameEStringParserRuleCall_3_1_0; }
		
		//('TopicRef' TopicRef=[ros::Subscriber|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'TopicRef'
		public Keyword getTopicRefKeyword_4_0() { return cTopicRefKeyword_4_0; }
		
		//TopicRef=[ros::Subscriber|EString]
		public Assignment getTopicRefAssignment_4_1() { return cTopicRefAssignment_4_1; }
		
		//[ros::Subscriber|EString]
		public CrossReference getTopicRefSubscriberCrossReference_4_1_0() { return cTopicRefSubscriberCrossReference_4_1_0; }
		
		//EString
		public RuleCall getTopicRefSubscriberEStringParserRuleCall_4_1_0_1() { return cTopicRefSubscriberEStringParserRuleCall_4_1_0_1; }
		
		//('NameSpace' NameSpace=[ros::Namespace|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'NameSpace'
		public Keyword getNameSpaceKeyword_5_0() { return cNameSpaceKeyword_5_0; }
		
		//NameSpace=[ros::Namespace|EString]
		public Assignment getNameSpaceAssignment_5_1() { return cNameSpaceAssignment_5_1; }
		
		//[ros::Namespace|EString]
		public CrossReference getNameSpaceNamespaceCrossReference_5_1_0() { return cNameSpaceNamespaceCrossReference_5_1_0; }
		
		//EString
		public RuleCall getNameSpaceNamespaceEStringParserRuleCall_5_1_0_1() { return cNameSpaceNamespaceEStringParserRuleCall_5_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class Publisher0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.Publisher0");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPublisherKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameGraphNameParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cMessageKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cMessageAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cMessageTopicSpecCrossReference_5_0 = (CrossReference)cMessageAssignment_5.eContents().get(0);
		private final RuleCall cMessageTopicSpecEStringParserRuleCall_5_0_1 = (RuleCall)cMessageTopicSpecCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cNamespaceKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cNamespaceAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cNamespaceNamespaceParserRuleCall_6_1_0 = (RuleCall)cNamespaceAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Publisher0 ros::Publisher:
		//	'Publisher'
		//	'{'
		//	'name' name=GraphName
		//	'message' message=[ros::TopicSpec|EString] ('namespace' namespace=Namespace)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Publisher' '{' 'name' name=GraphName 'message' message=[ros::TopicSpec|EString] ('namespace' namespace=Namespace)? '}'
		public Group getGroup() { return cGroup; }
		
		//'Publisher'
		public Keyword getPublisherKeyword_0() { return cPublisherKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'name'
		public Keyword getNameKeyword_2() { return cNameKeyword_2; }
		
		//name=GraphName
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//GraphName
		public RuleCall getNameGraphNameParserRuleCall_3_0() { return cNameGraphNameParserRuleCall_3_0; }
		
		//'message'
		public Keyword getMessageKeyword_4() { return cMessageKeyword_4; }
		
		//message=[ros::TopicSpec|EString]
		public Assignment getMessageAssignment_5() { return cMessageAssignment_5; }
		
		//[ros::TopicSpec|EString]
		public CrossReference getMessageTopicSpecCrossReference_5_0() { return cMessageTopicSpecCrossReference_5_0; }
		
		//EString
		public RuleCall getMessageTopicSpecEStringParserRuleCall_5_0_1() { return cMessageTopicSpecEStringParserRuleCall_5_0_1; }
		
		//('namespace' namespace=Namespace)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'namespace'
		public Keyword getNamespaceKeyword_6_0() { return cNamespaceKeyword_6_0; }
		
		//namespace=Namespace
		public Assignment getNamespaceAssignment_6_1() { return cNamespaceAssignment_6_1; }
		
		//Namespace
		public RuleCall getNamespaceNamespaceParserRuleCall_6_1_0() { return cNamespaceNamespaceParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class GraphNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.GraphName");
		private final Keyword cGraphNameKeyword = (Keyword)rule.eContents().get(1);
		
		//GraphName ros::GraphName:
		//	'GraphName' /* TODO: implement this rule and an appropriate IValueConverter */;
		@Override public ParserRule getRule() { return rule; }
		
		//'GraphName'
		public Keyword getGraphNameKeyword() { return cGraphNameKeyword; }
	}
	public class TopicSpecElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.TopicSpec");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTopicSpecAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTopicSpecKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cMessageKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cMessageAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cMessageMessageDefinitionParserRuleCall_4_1_0 = (RuleCall)cMessageAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//TopicSpec ros::TopicSpec:
		//	{ros::TopicSpec}
		//	'TopicSpec'
		//	name=EString
		//	'{' ('message' message=MessageDefinition)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ros::TopicSpec} 'TopicSpec' name=EString '{' ('message' message=MessageDefinition)? '}'
		public Group getGroup() { return cGroup; }
		
		//{ros::TopicSpec}
		public Action getTopicSpecAction_0() { return cTopicSpecAction_0; }
		
		//'TopicSpec'
		public Keyword getTopicSpecKeyword_1() { return cTopicSpecKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('message' message=MessageDefinition)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'message'
		public Keyword getMessageKeyword_4_0() { return cMessageKeyword_4_0; }
		
		//message=MessageDefinition
		public Assignment getMessageAssignment_4_1() { return cMessageAssignment_4_1; }
		
		//MessageDefinition
		public RuleCall getMessageMessageDefinitionParserRuleCall_4_1_0() { return cMessageMessageDefinitionParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class MessageDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.MessageDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMessageDefinitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMessageDefinitionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//MessageDefinition ros::MessageDefinition:
		//	{ros::MessageDefinition}
		//	'MessageDefinition';
		@Override public ParserRule getRule() { return rule; }
		
		//{ros::MessageDefinition} 'MessageDefinition'
		public Group getGroup() { return cGroup; }
		
		//{ros::MessageDefinition}
		public Action getMessageDefinitionAction_0() { return cMessageDefinitionAction_0; }
		
		//'MessageDefinition'
		public Keyword getMessageDefinitionKeyword_1() { return cMessageDefinitionKeyword_1; }
	}
	public class GlobalNamespaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.GlobalNamespace");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGlobalNamespaceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cGlobalNamespaceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPartsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cPartsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cPartsGraphNameParserRuleCall_3_2_0 = (RuleCall)cPartsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cPartsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cPartsGraphNameParserRuleCall_3_3_1_0 = (RuleCall)cPartsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//GlobalNamespace ros::GlobalNamespace:
		//	{ros::GlobalNamespace}
		//	'GlobalNamespace'
		//	'{' ('parts' '{' parts+=GraphName ("," parts+=GraphName)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ros::GlobalNamespace} 'GlobalNamespace' '{' ('parts' '{' parts+=GraphName ("," parts+=GraphName)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{ros::GlobalNamespace}
		public Action getGlobalNamespaceAction_0() { return cGlobalNamespaceAction_0; }
		
		//'GlobalNamespace'
		public Keyword getGlobalNamespaceKeyword_1() { return cGlobalNamespaceKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('parts' '{' parts+=GraphName ("," parts+=GraphName)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'parts'
		public Keyword getPartsKeyword_3_0() { return cPartsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//parts+=GraphName
		public Assignment getPartsAssignment_3_2() { return cPartsAssignment_3_2; }
		
		//GraphName
		public RuleCall getPartsGraphNameParserRuleCall_3_2_0() { return cPartsGraphNameParserRuleCall_3_2_0; }
		
		//("," parts+=GraphName)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//parts+=GraphName
		public Assignment getPartsAssignment_3_3_1() { return cPartsAssignment_3_3_1; }
		
		//GraphName
		public RuleCall getPartsGraphNameParserRuleCall_3_3_1_0() { return cPartsGraphNameParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class RelativeNamespace_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.RelativeNamespace_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRelativeNamespaceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRelativeNamespaceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPartsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cPartsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cPartsGraphNameParserRuleCall_3_2_0 = (RuleCall)cPartsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cPartsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cPartsGraphNameParserRuleCall_3_3_1_0 = (RuleCall)cPartsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//RelativeNamespace_Impl ros::RelativeNamespace:
		//	{ros::RelativeNamespace}
		//	'RelativeNamespace'
		//	'{' ('parts' '{' parts+=GraphName ("," parts+=GraphName)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ros::RelativeNamespace} 'RelativeNamespace' '{' ('parts' '{' parts+=GraphName ("," parts+=GraphName)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{ros::RelativeNamespace}
		public Action getRelativeNamespaceAction_0() { return cRelativeNamespaceAction_0; }
		
		//'RelativeNamespace'
		public Keyword getRelativeNamespaceKeyword_1() { return cRelativeNamespaceKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('parts' '{' parts+=GraphName ("," parts+=GraphName)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'parts'
		public Keyword getPartsKeyword_3_0() { return cPartsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//parts+=GraphName
		public Assignment getPartsAssignment_3_2() { return cPartsAssignment_3_2; }
		
		//GraphName
		public RuleCall getPartsGraphNameParserRuleCall_3_2_0() { return cPartsGraphNameParserRuleCall_3_2_0; }
		
		//("," parts+=GraphName)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//parts+=GraphName
		public Assignment getPartsAssignment_3_3_1() { return cPartsAssignment_3_3_1; }
		
		//GraphName
		public RuleCall getPartsGraphNameParserRuleCall_3_3_1_0() { return cPartsGraphNameParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class PrivateNamespaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.PrivateNamespace");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPrivateNamespaceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPrivateNamespaceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPartsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cPartsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cPartsGraphNameParserRuleCall_3_2_0 = (RuleCall)cPartsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cPartsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cPartsGraphNameParserRuleCall_3_3_1_0 = (RuleCall)cPartsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//PrivateNamespace ros::PrivateNamespace:
		//	{ros::PrivateNamespace}
		//	'PrivateNamespace'
		//	'{' ('parts' '{' parts+=GraphName ("," parts+=GraphName)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ros::PrivateNamespace} 'PrivateNamespace' '{' ('parts' '{' parts+=GraphName ("," parts+=GraphName)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{ros::PrivateNamespace}
		public Action getPrivateNamespaceAction_0() { return cPrivateNamespaceAction_0; }
		
		//'PrivateNamespace'
		public Keyword getPrivateNamespaceKeyword_1() { return cPrivateNamespaceKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('parts' '{' parts+=GraphName ("," parts+=GraphName)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'parts'
		public Keyword getPartsKeyword_3_0() { return cPartsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//parts+=GraphName
		public Assignment getPartsAssignment_3_2() { return cPartsAssignment_3_2; }
		
		//GraphName
		public RuleCall getPartsGraphNameParserRuleCall_3_2_0() { return cPartsGraphNameParserRuleCall_3_2_0; }
		
		//("," parts+=GraphName)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//parts+=GraphName
		public Assignment getPartsAssignment_3_3_1() { return cPartsAssignment_3_3_1; }
		
		//GraphName
		public RuleCall getPartsGraphNameParserRuleCall_3_3_1_0() { return cPartsGraphNameParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class Subscriber0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.Subscriber0");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSubscriberKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameGraphNameParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cMessageKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cMessageAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cMessageTopicSpecCrossReference_5_0 = (CrossReference)cMessageAssignment_5.eContents().get(0);
		private final RuleCall cMessageTopicSpecEStringParserRuleCall_5_0_1 = (RuleCall)cMessageTopicSpecCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cNamespaceKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cNamespaceAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cNamespaceNamespaceParserRuleCall_6_1_0 = (RuleCall)cNamespaceAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Subscriber0 ros::Subscriber:
		//	'Subscriber'
		//	'{'
		//	'name' name=GraphName
		//	'message' message=[ros::TopicSpec|EString] ('namespace' namespace=Namespace)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Subscriber' '{' 'name' name=GraphName 'message' message=[ros::TopicSpec|EString] ('namespace' namespace=Namespace)? '}'
		public Group getGroup() { return cGroup; }
		
		//'Subscriber'
		public Keyword getSubscriberKeyword_0() { return cSubscriberKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'name'
		public Keyword getNameKeyword_2() { return cNameKeyword_2; }
		
		//name=GraphName
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//GraphName
		public RuleCall getNameGraphNameParserRuleCall_3_0() { return cNameGraphNameParserRuleCall_3_0; }
		
		//'message'
		public Keyword getMessageKeyword_4() { return cMessageKeyword_4; }
		
		//message=[ros::TopicSpec|EString]
		public Assignment getMessageAssignment_5() { return cMessageAssignment_5; }
		
		//[ros::TopicSpec|EString]
		public CrossReference getMessageTopicSpecCrossReference_5_0() { return cMessageTopicSpecCrossReference_5_0; }
		
		//EString
		public RuleCall getMessageTopicSpecEStringParserRuleCall_5_0_1() { return cMessageTopicSpecEStringParserRuleCall_5_0_1; }
		
		//('namespace' namespace=Namespace)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'namespace'
		public Keyword getNamespaceKeyword_6_0() { return cNamespaceKeyword_6_0; }
		
		//namespace=Namespace
		public Assignment getNamespaceAssignment_6_1() { return cNamespaceAssignment_6_1; }
		
		//Namespace
		public RuleCall getNamespaceNamespaceParserRuleCall_6_1_0() { return cNamespaceNamespaceParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ServiceServerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.ServiceServer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cServiceServerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cServiceServerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cServiceNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cServiceNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cServiceNameEStringParserRuleCall_3_1_0 = (RuleCall)cServiceNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSrvRefKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSrvRefAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cSrvRefServiceServerCrossReference_4_1_0 = (CrossReference)cSrvRefAssignment_4_1.eContents().get(0);
		private final RuleCall cSrvRefServiceServerEStringParserRuleCall_4_1_0_1 = (RuleCall)cSrvRefServiceServerCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cNameSpaceKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cNameSpaceAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cNameSpaceNamespaceCrossReference_5_1_0 = (CrossReference)cNameSpaceAssignment_5_1.eContents().get(0);
		private final RuleCall cNameSpaceNamespaceEStringParserRuleCall_5_1_0_1 = (RuleCall)cNameSpaceNamespaceCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ServiceServer componentInterface::ServiceServer:
		//	{componentInterface::ServiceServer}
		//	'ServiceServer'
		//	'{' ('ServiceName' ServiceName=EString)? ('SrvRef' SrvRef=[ros::ServiceServer|EString])? ('NameSpace'
		//	NameSpace=[ros::Namespace|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{componentInterface::ServiceServer} 'ServiceServer' '{' ('ServiceName' ServiceName=EString)? ('SrvRef'
		//SrvRef=[ros::ServiceServer|EString])? ('NameSpace' NameSpace=[ros::Namespace|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{componentInterface::ServiceServer}
		public Action getServiceServerAction_0() { return cServiceServerAction_0; }
		
		//'ServiceServer'
		public Keyword getServiceServerKeyword_1() { return cServiceServerKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('ServiceName' ServiceName=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'ServiceName'
		public Keyword getServiceNameKeyword_3_0() { return cServiceNameKeyword_3_0; }
		
		//ServiceName=EString
		public Assignment getServiceNameAssignment_3_1() { return cServiceNameAssignment_3_1; }
		
		//EString
		public RuleCall getServiceNameEStringParserRuleCall_3_1_0() { return cServiceNameEStringParserRuleCall_3_1_0; }
		
		//('SrvRef' SrvRef=[ros::ServiceServer|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'SrvRef'
		public Keyword getSrvRefKeyword_4_0() { return cSrvRefKeyword_4_0; }
		
		//SrvRef=[ros::ServiceServer|EString]
		public Assignment getSrvRefAssignment_4_1() { return cSrvRefAssignment_4_1; }
		
		//[ros::ServiceServer|EString]
		public CrossReference getSrvRefServiceServerCrossReference_4_1_0() { return cSrvRefServiceServerCrossReference_4_1_0; }
		
		//EString
		public RuleCall getSrvRefServiceServerEStringParserRuleCall_4_1_0_1() { return cSrvRefServiceServerEStringParserRuleCall_4_1_0_1; }
		
		//('NameSpace' NameSpace=[ros::Namespace|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'NameSpace'
		public Keyword getNameSpaceKeyword_5_0() { return cNameSpaceKeyword_5_0; }
		
		//NameSpace=[ros::Namespace|EString]
		public Assignment getNameSpaceAssignment_5_1() { return cNameSpaceAssignment_5_1; }
		
		//[ros::Namespace|EString]
		public CrossReference getNameSpaceNamespaceCrossReference_5_1_0() { return cNameSpaceNamespaceCrossReference_5_1_0; }
		
		//EString
		public RuleCall getNameSpaceNamespaceEStringParserRuleCall_5_1_0_1() { return cNameSpaceNamespaceEStringParserRuleCall_5_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ServiceClientElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.ServiceClient");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cServiceClientAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cServiceClientKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cServiceNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cServiceNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cServiceNameEStringParserRuleCall_3_1_0 = (RuleCall)cServiceNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSrvRefKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSrvRefAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cSrvRefServiceClientCrossReference_4_1_0 = (CrossReference)cSrvRefAssignment_4_1.eContents().get(0);
		private final RuleCall cSrvRefServiceClientEStringParserRuleCall_4_1_0_1 = (RuleCall)cSrvRefServiceClientCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cNameSpaceKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cNameSpaceAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cNameSpaceNamespaceCrossReference_5_1_0 = (CrossReference)cNameSpaceAssignment_5_1.eContents().get(0);
		private final RuleCall cNameSpaceNamespaceEStringParserRuleCall_5_1_0_1 = (RuleCall)cNameSpaceNamespaceCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ServiceClient componentInterface::ServiceClient:
		//	{componentInterface::ServiceClient}
		//	'ServiceClient'
		//	'{' ('ServiceName' ServiceName=EString)? ('SrvRef' SrvRef=[ros::ServiceClient|EString])? ('NameSpace'
		//	NameSpace=[ros::Namespace|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{componentInterface::ServiceClient} 'ServiceClient' '{' ('ServiceName' ServiceName=EString)? ('SrvRef'
		//SrvRef=[ros::ServiceClient|EString])? ('NameSpace' NameSpace=[ros::Namespace|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{componentInterface::ServiceClient}
		public Action getServiceClientAction_0() { return cServiceClientAction_0; }
		
		//'ServiceClient'
		public Keyword getServiceClientKeyword_1() { return cServiceClientKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('ServiceName' ServiceName=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'ServiceName'
		public Keyword getServiceNameKeyword_3_0() { return cServiceNameKeyword_3_0; }
		
		//ServiceName=EString
		public Assignment getServiceNameAssignment_3_1() { return cServiceNameAssignment_3_1; }
		
		//EString
		public RuleCall getServiceNameEStringParserRuleCall_3_1_0() { return cServiceNameEStringParserRuleCall_3_1_0; }
		
		//('SrvRef' SrvRef=[ros::ServiceClient|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'SrvRef'
		public Keyword getSrvRefKeyword_4_0() { return cSrvRefKeyword_4_0; }
		
		//SrvRef=[ros::ServiceClient|EString]
		public Assignment getSrvRefAssignment_4_1() { return cSrvRefAssignment_4_1; }
		
		//[ros::ServiceClient|EString]
		public CrossReference getSrvRefServiceClientCrossReference_4_1_0() { return cSrvRefServiceClientCrossReference_4_1_0; }
		
		//EString
		public RuleCall getSrvRefServiceClientEStringParserRuleCall_4_1_0_1() { return cSrvRefServiceClientEStringParserRuleCall_4_1_0_1; }
		
		//('NameSpace' NameSpace=[ros::Namespace|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'NameSpace'
		public Keyword getNameSpaceKeyword_5_0() { return cNameSpaceKeyword_5_0; }
		
		//NameSpace=[ros::Namespace|EString]
		public Assignment getNameSpaceAssignment_5_1() { return cNameSpaceAssignment_5_1; }
		
		//[ros::Namespace|EString]
		public CrossReference getNameSpaceNamespaceCrossReference_5_1_0() { return cNameSpaceNamespaceCrossReference_5_1_0; }
		
		//EString
		public RuleCall getNameSpaceNamespaceEStringParserRuleCall_5_1_0_1() { return cNameSpaceNamespaceEStringParserRuleCall_5_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ServiceServer0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.ServiceServer0");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cServiceServerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameGraphNameParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cServiceKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cServiceAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cServiceServiceSpecCrossReference_5_0 = (CrossReference)cServiceAssignment_5.eContents().get(0);
		private final RuleCall cServiceServiceSpecEStringParserRuleCall_5_0_1 = (RuleCall)cServiceServiceSpecCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cNamespaceKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cNamespaceAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cNamespaceNamespaceParserRuleCall_6_1_0 = (RuleCall)cNamespaceAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//ServiceServer0 ros::ServiceServer:
		//	'ServiceServer'
		//	'{'
		//	'name' name=GraphName
		//	'service' service=[ros::ServiceSpec|EString] ('namespace' namespace=Namespace)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ServiceServer' '{' 'name' name=GraphName 'service' service=[ros::ServiceSpec|EString] ('namespace'
		//namespace=Namespace)? '}'
		public Group getGroup() { return cGroup; }
		
		//'ServiceServer'
		public Keyword getServiceServerKeyword_0() { return cServiceServerKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'name'
		public Keyword getNameKeyword_2() { return cNameKeyword_2; }
		
		//name=GraphName
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//GraphName
		public RuleCall getNameGraphNameParserRuleCall_3_0() { return cNameGraphNameParserRuleCall_3_0; }
		
		//'service'
		public Keyword getServiceKeyword_4() { return cServiceKeyword_4; }
		
		//service=[ros::ServiceSpec|EString]
		public Assignment getServiceAssignment_5() { return cServiceAssignment_5; }
		
		//[ros::ServiceSpec|EString]
		public CrossReference getServiceServiceSpecCrossReference_5_0() { return cServiceServiceSpecCrossReference_5_0; }
		
		//EString
		public RuleCall getServiceServiceSpecEStringParserRuleCall_5_0_1() { return cServiceServiceSpecEStringParserRuleCall_5_0_1; }
		
		//('namespace' namespace=Namespace)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'namespace'
		public Keyword getNamespaceKeyword_6_0() { return cNamespaceKeyword_6_0; }
		
		//namespace=Namespace
		public Assignment getNamespaceAssignment_6_1() { return cNamespaceAssignment_6_1; }
		
		//Namespace
		public RuleCall getNamespaceNamespaceParserRuleCall_6_1_0() { return cNamespaceNamespaceParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ServiceSpecElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.ServiceSpec");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cServiceSpecAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cServiceSpecKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRequestKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRequestAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cRequestMessageDefinitionParserRuleCall_4_1_0 = (RuleCall)cRequestAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cResponseKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cResponseAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cResponseMessageDefinitionParserRuleCall_5_1_0 = (RuleCall)cResponseAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ServiceSpec ros::ServiceSpec:
		//	{ros::ServiceSpec}
		//	'ServiceSpec'
		//	name=EString
		//	'{' ('request' request=MessageDefinition)? ('response' response=MessageDefinition)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ros::ServiceSpec} 'ServiceSpec' name=EString '{' ('request' request=MessageDefinition)? ('response'
		//response=MessageDefinition)? '}'
		public Group getGroup() { return cGroup; }
		
		//{ros::ServiceSpec}
		public Action getServiceSpecAction_0() { return cServiceSpecAction_0; }
		
		//'ServiceSpec'
		public Keyword getServiceSpecKeyword_1() { return cServiceSpecKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('request' request=MessageDefinition)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'request'
		public Keyword getRequestKeyword_4_0() { return cRequestKeyword_4_0; }
		
		//request=MessageDefinition
		public Assignment getRequestAssignment_4_1() { return cRequestAssignment_4_1; }
		
		//MessageDefinition
		public RuleCall getRequestMessageDefinitionParserRuleCall_4_1_0() { return cRequestMessageDefinitionParserRuleCall_4_1_0; }
		
		//('response' response=MessageDefinition)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'response'
		public Keyword getResponseKeyword_5_0() { return cResponseKeyword_5_0; }
		
		//response=MessageDefinition
		public Assignment getResponseAssignment_5_1() { return cResponseAssignment_5_1; }
		
		//MessageDefinition
		public RuleCall getResponseMessageDefinitionParserRuleCall_5_1_0() { return cResponseMessageDefinitionParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ServiceClient0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.RosSystem.ServiceClient0");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cServiceClientKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameGraphNameParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cServiceKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cServiceAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cServiceServiceSpecCrossReference_5_0 = (CrossReference)cServiceAssignment_5.eContents().get(0);
		private final RuleCall cServiceServiceSpecEStringParserRuleCall_5_0_1 = (RuleCall)cServiceServiceSpecCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cNamespaceKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cNamespaceAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cNamespaceNamespaceParserRuleCall_6_1_0 = (RuleCall)cNamespaceAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//ServiceClient0 ros::ServiceClient:
		//	'ServiceClient'
		//	'{'
		//	'name' name=GraphName
		//	'service' service=[ros::ServiceSpec|EString] ('namespace' namespace=Namespace)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ServiceClient' '{' 'name' name=GraphName 'service' service=[ros::ServiceSpec|EString] ('namespace'
		//namespace=Namespace)? '}'
		public Group getGroup() { return cGroup; }
		
		//'ServiceClient'
		public Keyword getServiceClientKeyword_0() { return cServiceClientKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'name'
		public Keyword getNameKeyword_2() { return cNameKeyword_2; }
		
		//name=GraphName
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//GraphName
		public RuleCall getNameGraphNameParserRuleCall_3_0() { return cNameGraphNameParserRuleCall_3_0; }
		
		//'service'
		public Keyword getServiceKeyword_4() { return cServiceKeyword_4; }
		
		//service=[ros::ServiceSpec|EString]
		public Assignment getServiceAssignment_5() { return cServiceAssignment_5; }
		
		//[ros::ServiceSpec|EString]
		public CrossReference getServiceServiceSpecCrossReference_5_0() { return cServiceServiceSpecCrossReference_5_0; }
		
		//EString
		public RuleCall getServiceServiceSpecEStringParserRuleCall_5_0_1() { return cServiceServiceSpecEStringParserRuleCall_5_0_1; }
		
		//('namespace' namespace=Namespace)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'namespace'
		public Keyword getNamespaceKeyword_6_0() { return cNamespaceKeyword_6_0; }
		
		//namespace=Namespace
		public Assignment getNamespaceAssignment_6_1() { return cNamespaceAssignment_6_1; }
		
		//Namespace
		public RuleCall getNamespaceNamespaceParserRuleCall_6_1_0() { return cNamespaceNamespaceParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	
	private final RosSystemElements pRosSystem;
	private final NamespaceElements pNamespace;
	private final TopicConnectionElements pTopicConnection;
	private final ServiceConnectionElements pServiceConnection;
	private final EStringElements pEString;
	private final ComponentInterfaceElements pComponentInterface;
	private final PublisherElements pPublisher;
	private final SubscriberElements pSubscriber;
	private final Publisher0Elements pPublisher0;
	private final GraphNameElements pGraphName;
	private final TopicSpecElements pTopicSpec;
	private final MessageDefinitionElements pMessageDefinition;
	private final GlobalNamespaceElements pGlobalNamespace;
	private final RelativeNamespace_ImplElements pRelativeNamespace_Impl;
	private final PrivateNamespaceElements pPrivateNamespace;
	private final Subscriber0Elements pSubscriber0;
	private final ServiceServerElements pServiceServer;
	private final ServiceClientElements pServiceClient;
	private final ServiceServer0Elements pServiceServer0;
	private final ServiceSpecElements pServiceSpec;
	private final ServiceClient0Elements pServiceClient0;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RosSystemGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRosSystem = new RosSystemElements();
		this.pNamespace = new NamespaceElements();
		this.pTopicConnection = new TopicConnectionElements();
		this.pServiceConnection = new ServiceConnectionElements();
		this.pEString = new EStringElements();
		this.pComponentInterface = new ComponentInterfaceElements();
		this.pPublisher = new PublisherElements();
		this.pSubscriber = new SubscriberElements();
		this.pPublisher0 = new Publisher0Elements();
		this.pGraphName = new GraphNameElements();
		this.pTopicSpec = new TopicSpecElements();
		this.pMessageDefinition = new MessageDefinitionElements();
		this.pGlobalNamespace = new GlobalNamespaceElements();
		this.pRelativeNamespace_Impl = new RelativeNamespace_ImplElements();
		this.pPrivateNamespace = new PrivateNamespaceElements();
		this.pSubscriber0 = new Subscriber0Elements();
		this.pServiceServer = new ServiceServerElements();
		this.pServiceClient = new ServiceClientElements();
		this.pServiceServer0 = new ServiceServer0Elements();
		this.pServiceSpec = new ServiceSpecElements();
		this.pServiceClient0 = new ServiceClient0Elements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.fraunhofer.ipa.RosSystem".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RosSystem:
	//	{RosSystem}
	//	'RosSystem'
	//	'{' ('Name' Name=EString)? ('RosComponent' RosComponent+=[componentInterface::ComponentInterface|EString])?
	//	('TopicConnections' '{' TopicConnections+=TopicConnection ("," TopicConnections+=TopicConnection)* '}')?
	//	('ServiceConnections' '{' ServiceConnections+=ServiceConnection ("," ServiceConnections+=ServiceConnection)* '}')?
	//	'}';
	public RosSystemElements getRosSystemAccess() {
		return pRosSystem;
	}
	
	public ParserRule getRosSystemRule() {
		return getRosSystemAccess().getRule();
	}
	
	//Namespace ros::Namespace:
	//	GlobalNamespace | RelativeNamespace_Impl | PrivateNamespace;
	public NamespaceElements getNamespaceAccess() {
		return pNamespace;
	}
	
	public ParserRule getNamespaceRule() {
		return getNamespaceAccess().getRule();
	}
	
	//TopicConnection:
	//	{TopicConnection}
	//	'TopicConnection'
	//	'{' ('From' From=[componentInterface::Publisher|EString])? ('To' To=[componentInterface::Subscriber|EString])?
	//	'}';
	public TopicConnectionElements getTopicConnectionAccess() {
		return pTopicConnection;
	}
	
	public ParserRule getTopicConnectionRule() {
		return getTopicConnectionAccess().getRule();
	}
	
	//ServiceConnection:
	//	{ServiceConnection}
	//	'ServiceConnection'
	//	'{' ('From' From=[componentInterface::ServiceServer|EString])? ('To' To=[componentInterface::ServiceClient|EString])?
	//	'}';
	public ServiceConnectionElements getServiceConnectionAccess() {
		return pServiceConnection;
	}
	
	public ParserRule getServiceConnectionRule() {
		return getServiceConnectionAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//ComponentInterface componentInterface::ComponentInterface:
	//	'ComponentInterface'
	//	'{'
	//	'name' name=EString ('namespace' namespace=Namespace)? ('publisher' RosTopicPublisher+=Publisher)? ('subscriber'
	//	RosTopicSubscriber+=Subscriber)? ('serviceServer' RosServiceServer+=ServiceServer)? ('serviceClient'
	//	RosServiceClient+=ServiceClient)?
	//	'}';
	public ComponentInterfaceElements getComponentInterfaceAccess() {
		return pComponentInterface;
	}
	
	public ParserRule getComponentInterfaceRule() {
		return getComponentInterfaceAccess().getRule();
	}
	
	//Publisher componentInterface::Publisher:
	//	{componentInterface::Publisher}
	//	'Publisher'
	//	'{' ('TopicName' TopicName=EString)? ('TopicRef' TopicRef=[ros::Publisher|EString])? ('NameSpace'
	//	NameSpace=[ros::Namespace|EString])?
	//	'}';
	public PublisherElements getPublisherAccess() {
		return pPublisher;
	}
	
	public ParserRule getPublisherRule() {
		return getPublisherAccess().getRule();
	}
	
	//Subscriber componentInterface::Subscriber:
	//	{componentInterface::Subscriber}
	//	'Subscriber'
	//	'{' ('TopicName' TopicName=EString)? ('TopicRef' TopicRef=[ros::Subscriber|EString])? ('NameSpace'
	//	NameSpace=[ros::Namespace|EString])?
	//	'}';
	public SubscriberElements getSubscriberAccess() {
		return pSubscriber;
	}
	
	public ParserRule getSubscriberRule() {
		return getSubscriberAccess().getRule();
	}
	
	//Publisher0 ros::Publisher:
	//	'Publisher'
	//	'{'
	//	'name' name=GraphName
	//	'message' message=[ros::TopicSpec|EString] ('namespace' namespace=Namespace)?
	//	'}';
	public Publisher0Elements getPublisher0Access() {
		return pPublisher0;
	}
	
	public ParserRule getPublisher0Rule() {
		return getPublisher0Access().getRule();
	}
	
	//GraphName ros::GraphName:
	//	'GraphName' /* TODO: implement this rule and an appropriate IValueConverter */;
	public GraphNameElements getGraphNameAccess() {
		return pGraphName;
	}
	
	public ParserRule getGraphNameRule() {
		return getGraphNameAccess().getRule();
	}
	
	//TopicSpec ros::TopicSpec:
	//	{ros::TopicSpec}
	//	'TopicSpec'
	//	name=EString
	//	'{' ('message' message=MessageDefinition)?
	//	'}';
	public TopicSpecElements getTopicSpecAccess() {
		return pTopicSpec;
	}
	
	public ParserRule getTopicSpecRule() {
		return getTopicSpecAccess().getRule();
	}
	
	//MessageDefinition ros::MessageDefinition:
	//	{ros::MessageDefinition}
	//	'MessageDefinition';
	public MessageDefinitionElements getMessageDefinitionAccess() {
		return pMessageDefinition;
	}
	
	public ParserRule getMessageDefinitionRule() {
		return getMessageDefinitionAccess().getRule();
	}
	
	//GlobalNamespace ros::GlobalNamespace:
	//	{ros::GlobalNamespace}
	//	'GlobalNamespace'
	//	'{' ('parts' '{' parts+=GraphName ("," parts+=GraphName)* '}')?
	//	'}';
	public GlobalNamespaceElements getGlobalNamespaceAccess() {
		return pGlobalNamespace;
	}
	
	public ParserRule getGlobalNamespaceRule() {
		return getGlobalNamespaceAccess().getRule();
	}
	
	//RelativeNamespace_Impl ros::RelativeNamespace:
	//	{ros::RelativeNamespace}
	//	'RelativeNamespace'
	//	'{' ('parts' '{' parts+=GraphName ("," parts+=GraphName)* '}')?
	//	'}';
	public RelativeNamespace_ImplElements getRelativeNamespace_ImplAccess() {
		return pRelativeNamespace_Impl;
	}
	
	public ParserRule getRelativeNamespace_ImplRule() {
		return getRelativeNamespace_ImplAccess().getRule();
	}
	
	//PrivateNamespace ros::PrivateNamespace:
	//	{ros::PrivateNamespace}
	//	'PrivateNamespace'
	//	'{' ('parts' '{' parts+=GraphName ("," parts+=GraphName)* '}')?
	//	'}';
	public PrivateNamespaceElements getPrivateNamespaceAccess() {
		return pPrivateNamespace;
	}
	
	public ParserRule getPrivateNamespaceRule() {
		return getPrivateNamespaceAccess().getRule();
	}
	
	//Subscriber0 ros::Subscriber:
	//	'Subscriber'
	//	'{'
	//	'name' name=GraphName
	//	'message' message=[ros::TopicSpec|EString] ('namespace' namespace=Namespace)?
	//	'}';
	public Subscriber0Elements getSubscriber0Access() {
		return pSubscriber0;
	}
	
	public ParserRule getSubscriber0Rule() {
		return getSubscriber0Access().getRule();
	}
	
	//ServiceServer componentInterface::ServiceServer:
	//	{componentInterface::ServiceServer}
	//	'ServiceServer'
	//	'{' ('ServiceName' ServiceName=EString)? ('SrvRef' SrvRef=[ros::ServiceServer|EString])? ('NameSpace'
	//	NameSpace=[ros::Namespace|EString])?
	//	'}';
	public ServiceServerElements getServiceServerAccess() {
		return pServiceServer;
	}
	
	public ParserRule getServiceServerRule() {
		return getServiceServerAccess().getRule();
	}
	
	//ServiceClient componentInterface::ServiceClient:
	//	{componentInterface::ServiceClient}
	//	'ServiceClient'
	//	'{' ('ServiceName' ServiceName=EString)? ('SrvRef' SrvRef=[ros::ServiceClient|EString])? ('NameSpace'
	//	NameSpace=[ros::Namespace|EString])?
	//	'}';
	public ServiceClientElements getServiceClientAccess() {
		return pServiceClient;
	}
	
	public ParserRule getServiceClientRule() {
		return getServiceClientAccess().getRule();
	}
	
	//ServiceServer0 ros::ServiceServer:
	//	'ServiceServer'
	//	'{'
	//	'name' name=GraphName
	//	'service' service=[ros::ServiceSpec|EString] ('namespace' namespace=Namespace)?
	//	'}';
	public ServiceServer0Elements getServiceServer0Access() {
		return pServiceServer0;
	}
	
	public ParserRule getServiceServer0Rule() {
		return getServiceServer0Access().getRule();
	}
	
	//ServiceSpec ros::ServiceSpec:
	//	{ros::ServiceSpec}
	//	'ServiceSpec'
	//	name=EString
	//	'{' ('request' request=MessageDefinition)? ('response' response=MessageDefinition)?
	//	'}';
	public ServiceSpecElements getServiceSpecAccess() {
		return pServiceSpec;
	}
	
	public ParserRule getServiceSpecRule() {
		return getServiceSpecAccess().getRule();
	}
	
	//ServiceClient0 ros::ServiceClient:
	//	'ServiceClient'
	//	'{'
	//	'name' name=GraphName
	//	'service' service=[ros::ServiceSpec|EString] ('namespace' namespace=Namespace)?
	//	'}';
	public ServiceClient0Elements getServiceClient0Access() {
		return pServiceClient0;
	}
	
	public ParserRule getServiceClient0Rule() {
		return getServiceClient0Access().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
